### ISSUE TITLE
APK Download?

### ISSUE THREAD

**Issue by IzzySoft** [lmu-informatics/app-ins-gruene#18]
Currently the app seems to be available only in Google's walled garden. Would you consider making the APK available to those not having access there – like, attaching it to your [releases](https://github.com/mimuc/app-ins-gruene/releases), or bringing it to [F-Droid](https://f-droid.org/)? Thanks in advance!

**Comment by Gustl22** [comment]
The last released app version already can be downloaded in the releases section.
Or did you have trouble installing the apk?

**Comment by IzzySoft** [comment]
Ah, my bad. I saw the link on the "main page" just mentioned "tags" – which usually means "no releases", but doesn't take pre-releases into account. Apologies!
